- name: call common role
  import_role:
  #include_role: 
    name: common
  tags:
  - hi
  # tags will not be respected and cascaded by include_role, but import_role will respect the tags
  # import_role parse the playbook before execution, include_role parse the playbook at the time of exeution
  when: os == "RedHat"
  loop:
  - manisha
  - nithisha
