- name: common role msg-1
  debug: 
    msg: "Hi, I'am from common role MSG-1"

- name: common role msg-2
  debug:
    msg: "Hi, I'am from common role MSG-2 {{ item }}"

- name: common role msg-3
  debug: 
    msg: "Hi, I'am from common role MSG-3"


- name: change the fact
  set_fact: # set_fact is a module used to set the variable fact means variable, it will create the variables dynamically within the playbook, if we want to create the variables within playbook then we can use set_fact
    os: "Debian" # overriding previous loaded variable

- name: common role msg-4
  debug: 
    msg: "Hi, I'am from common role MSG-4"

# - name: call role-2
#   #import_role: # import_role checks the syntax before the execution and it will stop the execution if there is any issue
#   include_role: # include_role won't check the syntax first it will execute, include_role checks dynamically
#    name: role-3
